version: '3.8'
services:
  db:
    build: 
      context: .
      dockerfile: postgresql/Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  app:
    build: 
      context: .
      dockerfile: nodejs/Dockerfile
volumes:
  postgres-data: